apiVersion: 1

contactPoints:
  - orgId: 1
    name: email
    receivers:
      - uid: email-taylor
        type: email
        settings:
          addresses: taylor.r.meador@gmail.com

policies:
  - orgId: 1
    receiver: email
    group_by: ['alertname']
    repeat_interval: 12h

groups:
  - orgId: 1
    name: homelab
    folder: Homelab
    interval: 1m
    rules:
      - uid: host-down
        title: Host down
        condition: C
        data:
          - refId: A
            relativeTimeRange: { from: 600, to: 0 }
            datasourceUid: prometheus
            model:
              refId: A
              expr: up{job="integrations/unix"}
              instant: true
          - refId: C
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              expression: A
              conditions:
                - evaluator: { type: lt, params: [1] }
        for: 5m
        noDataState: Alerting
        execErrState: Alerting
        annotations:
          summary: 'Host {{ $labels.host }} is down'
