- targets: ['https://srv1.lab.taylor-meador.com:8006']
  labels:
    service: pve-srv1
- targets: ['https://srv2.lab.taylor-meador.com:8006']
  labels:
    service: pve-srv2
- targets: ['https://pbs-vm.lab.taylor-meador.com:8007']
  labels:
    service: pbs
