- targets: ['https://10.0.10.101:8006']
  labels:
        service: pve-srv1
- targets: ['https://10.0.10.102:8006']
  labels:
        service: pve-srv2
- targets: ['https://10.0.10.113:8007']
  labels:
        service: pbs
