all:
  children:
    opnsense:
      hosts:
        opnsense:
          ansible_host: 10.0.10.1

    hypervisors:
      hosts:
        srv1:
          ansible_host: srv1.lab.taylor-meador.com
        srv2:
          ansible_host: srv2.lab.taylor-meador.com

    containers:
      hosts:
        dev-ct:
          ansible_host: dev-ct.lab.taylor-meador.com
        minecraft-ct:
          ansible_host: minecraft-ct.lab.taylor-meador.com
        nginx-ct:
          ansible_host: nginx-ct.lab.taylor-meador.com
        monitoring-ct:
          ansible_host: monitoring-ct.lab.taylor-meador.com
        jellyfin-ct:
          ansible_host: jellyfin-ct.lab.taylor-meador.com

    vms:
      hosts:
        pbs-vm:
          ansible_host: pbs-vm.lab.taylor-meador.com
        torrent-vm:
          ansible_host: torrent-vm.lab.taylor-meador.com
        postgres-vm:
          ansible_host: postgres-vm.lab.taylor-meador.com
