- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg
    state: present
    update_cache: true

- name: Add Jellyfin GPG key
  ansible.builtin.get_url:
    url: https://repo.jellyfin.org/jellyfin_team.gpg.key
    dest: /etc/apt/keyrings/jellyfin.asc
    mode: "0644"

- name: Add Jellyfin apt repository
  ansible.builtin.deb822_repository:
    name: jellyfin
    uris: https://repo.jellyfin.org/debian
    suites: trixie
    components: main
    signed_by: /etc/apt/keyrings/jellyfin.asc
    state: present

- name: Install Jellyfin
  ansible.builtin.apt:
    name: jellyfin
    state: present
    update_cache: true

- name: Enable and start Jellyfin
  ansible.builtin.service:
    name: jellyfin
    state: started
    enabled: true
