- name: restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: restart blackbox
  ansible.builtin.service:
    name: prometheus-blackbox-exporter
    state: restarted

- name: restart grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted
