- name: Set up Loki and Prometheus remote write on monitoring-ct
  hosts: monitoring-ct
  become: true
  roles:
    - loki
    - monitoring

- name: Deploy Alloy to all nodes
  hosts: hypervisors:containers:vms
  become: true
  roles:
    - alloy
