- name: Configure NFS exports on srv1
  hosts: srv1
  become: true
  vars:
    nfs_exports:
      - path: /mnt/hdd-3tb
  roles:
    - nfs_server

- name: Configure NFS exports on srv2
  hosts: srv2
  become: true
  vars:
    nfs_exports:
      - path: /mnt/hdd-2tb
      - path: /mnt/hdd-6tb
  roles:
    - nfs_server
